package:
  name: hdf5
  version: 1.8.16

source:
  fn: hdf5-1.8.16.tar.bz2
  url: https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.bz2
  md5: 79c1593573ebddf734eee8d43ecfe483

build:
  number: 0

requirements:
  build:
    - zlib
  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
